language: node_js
node_js:
  - node

script:
- yarn run tsc greeter.ts
# --module commonjs 
- if $? then ; node greeter.js; fi

after_script:
- cat greeter.js
- npm run
- ls --color
- ls --color node_modules/.bin
- yarn help run
- yarn help exec
- yarn --help
- yarn run tsc --help
