language: node_js
node_js:
  - node

script:
- yarn run tsc greeter.ts

after_script:
- cat greeter.js
- npm run
- ls --color
- ls --color node_modules/.bin
- yarn run --help
- yarn exec --help
- yarn --help
